accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from accounts.views import register_new_user


urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", register_new_user, name="signup"),
]

price_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("tracker/", include("tracker.urls")),
    path("", RedirectView.as_view(url="/tracker/"), name="home"),
]

tracker/urls.py
from django.urls import path

from tracker.views import (
    ProductCreateView,
    ProductDeleteView,
    ProductListView,
    update_product,
)

urlpatterns = [
    path("", ProductListView.as_view(), name="list_products"),
    path("create/", ProductCreateView.as_view(), name="create_products"),
    path("<int:pk>/", update_product, name="update_product"),
    path(
        "<int:pk>/delete", ProductDeleteView.as_view(), name="delete_product"
    ),
]

tracker/models.py
from django.db import models
from django.conf import settings
from django.core.exceptions import ValidationError

USER_MODEL = settings.AUTH_USER_MODEL


def amazon_only_validator(value):
    if "amazon.com" in value:
        return value
    else:
        raise ValidationError(
            "Right now this only works for products on Amazon."
        )


class Product(models.Model):
    name = models.CharField(max_length=100)
    initial_price = models.DecimalField(max_digits=8, decimal_places=2)
    current_price = models.DecimalField(max_digits=8, decimal_places=2)
    reference_url = models.URLField(
        max_length=200,
        validators=[amazon_only_validator],
    )
    owner = models.ForeignKey(
        USER_MODEL, related_name="product", on_delete=models.CASCADE
    )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    picture_url = models.URLField(blank=True)

    def __str__(self):
        return self.name

accounts/views.py
from django.contrib.auth import login
from django.shortcuts import redirect, render
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


def register_new_user(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)

        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username, password=password
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()

    context = {"form": form}
    return render(request, "registration/signup.html", context)

tracker/views.py
from django.views.generic import CreateView, ListView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy

from tracker.models import Product
from tracker.scripts.utils import update_price_data, get_product_data


class ProductListView(LoginRequiredMixin, ListView):
    model = Product
    template_name = "products/list.html"

    def get_queryset(self):
        return Product.objects.filter(owner=self.request.user)


@login_required()
def update_product(request, pk):
    user = request.user

    product = get_object_or_404(Product, pk=pk, owner=user)

    if request.method == "POST":
        new_price = update_price_data(product)
        Product.objects.filter(pk=pk).update(current_price=new_price)
        return redirect("home")


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    template_name = "products/create.html"
    fields = ["name", "reference_url"]

    def form_valid(self, form):
        item = form.save(commit=False)

        try:
            price, picture_url = get_product_data(item)

            item.owner = self.request.user
            item.initial_price = price
            item.current_price = price
            item.picture_url = picture_url

            item.save()
            return redirect("home")
        except AttributeError:
            return self.form_invalid(form)

    def form_invalid(self, form):
        messages.warning(
            self.request,
            "Invalid URL."
            "Please double check that it links directly to a product.",
        )
        return self.render_to_response(
            self.get_context_data(request=self.request, form=form)
        )


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy("home")

tracker/templates/base.html
{% load bootstrap5 %} {% bootstrap_css %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>
            {% block title %}Matt's Price Tracker {% endblock title %}
        </title>
    </head>
    <body>
        <header>
            <nav
                class="navbar navbar-light navbar-expand-md"
                style="background-color: #e3f2fd"
            >
                <ul class="navbar-nav d-flex justify-content-end">
                    {% if user.is_authenticated %}
                    <li class="p2 nav-item">
                        <a class="nav-link" href="{% url 'create_products' %}"
                            >Add New Product</a
                        >
                    </li>
                    <li class="p2 nav-item">
                        <a class="nav-link" href="{% url 'home' %}"
                            >My Tracked Products</a
                        >
                    </li>
                    <li class="p2 nav-item">
                        <a class="nav-link" href="{% url 'logout' %}"
                            >Logout ({{ user.username }})</a
                        >
                    </li>
                    {% else %}
                    <li class="p2 nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                    <li class="p2 nav-item">
                        <a class="nav-link" href="{% url 'signup' %}">Signup</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <div class="container">{% block content %} {% endblock content %}</div>
    </body>
</html>

tracker/templates/products/create.html
<!-- prettier-ignore -->
{% extends 'base.html' %} {% block title %}Start Tracking a New Product{% endblock title %}
{% load bootstrap5 %} {% bootstrap_css %} {% bootstrap_javascript%}

<!-- prettier-ignore -->
{% block content %}
<main>
    <div>
        <h1 class="text-center">Start Tracking a New Product</h1>
        <div style="max-width: 50vw; margin: auto">
        <form method="post">
            <!-- prettier-ignore -->
            {% csrf_token %}
            {% bootstrap_form form %}
            {% comment %} {{ form.as_p }} {% endcomment %}


            <!-- prettier-ignore -->
                    {% if form.errors %} 
                        <div style="display: none;" >
                    {% else %}
                        <div>
                    {% endif %}
                        {% bootstrap_messages %}
                        </div>
            {% buttons %}
            <button>Create!</button>
            {% endbuttons %}
        </form>
    </div>
    </div>
</main>
{% endblock content %}

tracker/templates/products/list.html
<!-- prettier-ignore -->
{% extends 'base.html' %} {% block title %}My Tracked Products{% endblock title %}
{% load bootstrap5 %} {% bootstrap_css %} {% bootstrap_javascript%}

<!-- prettier-ignore -->
{% block content %}
<main>
    <div>
        <h1 class="text-center">My Tracked Products</h1>
        {% if product_list.all|length > 0 %}
        <table class="table">
            <thead>
                <th></th>
                <th>Product</th>
                <th>Initial Price</th>
                <th>Current Price</th>
            </thead>
            <tbody>
                {% for product in product_list %}
                <tr>
                    <td>
                        <img
                            style="height: 5rem"
                            src="{{ product.picture_url }}"
                            alt="Product Image"
                        />
                    </td>
                    <td>{{ product.name }}</td>
                    <td>${{ product.initial_price }}</td>
                    {% if product.current_price < product.initial_price %}
                    <td style="color: green">
                        {% elif product.current_price > product.initial_price %}
                    </td>

                    <td style="color: red">{% else %}</td>

                    <td>{% endif %} ${{ product.current_price }}</td>
                    <td>
                        <form
                            action="{% url 'update_product' product.pk %}"
                            method="post"
                        >
                            {% csrf_token %}
                            <input
                                type="hidden"
                                name="update_price"
                                value="{{ product }}"
                            />
                            <button>Update Price</button>
                        </form>
                    </td>
                    <td>
                        <form
                            action="{% url 'delete_product' product.pk %}"
                            method="post"
                        >
                            {% csrf_token %}
                            <input type="hidden" name="delete" />
                            <button>Delete</button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p>You have no tracked products</p>
        {% endif %}
    </div>
</main>
{% endblock content %}